name: freelance_app
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev



environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  webview_flutter:
  flutter:
    sdk: flutter
  splashscreen:
  google_fonts: ^1.1.0
  flutter_responsive_screen: ^1.0.0
  get: ^2.5.6
  animator: ^2.0.0
  device_preview: ^0.4.5
  smooth_star_rating: ^1.1.1
  eva_icons_flutter: ^2.0.0
  flutter_svg: ^0.17.4
  carousel_pro: ^1.0.0
  shared_preferences: ^0.5.7
  dio: ^3.0.9
  http: ^0.12.1
  progress_dialog: ^1.2.2
  file_picker: ^1.10.0
  cloud_firestore:
  firebase_messaging:
  firebase_storage:
  cupertino_icons: ^0.1.2
  firebase_core:
  firebase_database:
  flutter_local_notifications:
  image_picker:
  cached_network_image:
  intl:
  flutter_document_picker:
  open_file:
  permission_handler:
  agora_rtc_engine:
  fluttertoast:
  rating_bar:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.0"



flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/images/logobluewhite.png"
  image_path_android: "assets/images/logobluewhite.png"
  adaptive_icon_background: "assets/images/background.png"
  adaptive_icon_foreground: "assets/images/logobluewhite.png"

flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
